version: "3.4"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:5.6
    environment:
       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-email}    
       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
       PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT:-80}
    ports:
      - "8080:80"
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - ".env"
    ports:
      - "127.0.0.1:6379:6379"
volumes:
  postgres_data: {}

